-- HKG-T24-001 foundation schema asset.
-- Source of truth: hkg_t24.db.ddl.FOUNDATION_SQL.
-- This reviewed SQL asset documents the durable objects created by the CLI:
--   model_core.run_manifest
--   model_core.source_registry
--   model_core.cutoff_calendar
--   model_core.target_label
--   model_features.h24n_snapshot
--   model_features.nwp_safe_row_ledger
--   model_features.feature_matrix
--   model_features.v_nwp_forecast_wide_compat
--   model_features.v_raw_response_object_compat
--   model_features.v_nwp_h24n_safe_rows
--   model_validation.leakage_audit_event
--   model_validation.scoreboard
--   model_validation.negative_control_result
--   model_live.prediction
--   model_live.live_prediction_component
--   model_eval.system_prediction_component
--
-- Execute through:
--   python -m hkg_t24.cli phase0-preflight
--   python -m hkg_t24.cli build-source-registry
--   python -m hkg_t24.cli build-h24n-snapshots
