station_map:
  KNYC: USW00094728
  KLGA: USW00014732
  KMIA: USW00012839

defaults:
  dataset: daily-summaries
  datatype: TMAX
  units: standard
  format: json
  include_attributes: true
  year_chunking: true
