CREATE TABLE IF NOT EXISTS station_registry (
  station_key TEXT PRIMARY KEY,
  display_name TEXT NOT NULL,
  timezone TEXT NOT NULL,
  latitude REAL NOT NULL,
  longitude REAL NOT NULL,
  elevation_m REAL,
  metar_reset_minute INTEGER,
  aliases_json TEXT NOT NULL,
  metadata_json TEXT,
  created_at_utc TEXT NOT NULL,
  updated_at_utc TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS source_registry (
  source_name TEXT PRIMARY KEY,
  source_family TEXT NOT NULL,
  enabled INTEGER NOT NULL,
  base_url TEXT,
  config_json TEXT,
  created_at_utc TEXT NOT NULL,
  updated_at_utc TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ingest_job_run (
  run_id TEXT PRIMARY KEY,
  job_id TEXT NOT NULL,
  station_key TEXT,
  started_at_utc TEXT NOT NULL,
  finished_at_utc TEXT,
  status TEXT NOT NULL,
  total_requests INTEGER NOT NULL DEFAULT 0,
  succeeded INTEGER NOT NULL DEFAULT 0,
  failed INTEGER NOT NULL DEFAULT 0,
  skipped INTEGER NOT NULL DEFAULT 0,
  deduped INTEGER NOT NULL DEFAULT 0,
  total_bytes INTEGER NOT NULL DEFAULT 0,
  total_rows INTEGER NOT NULL DEFAULT 0,
  min_request_duration_ms REAL,
  mean_request_duration_ms REAL,
  p95_request_duration_ms REAL,
  throughput_mb_s REAL,
  parser_failures_json TEXT,
  missing_counts_json TEXT,
  summary_json TEXT
);

CREATE TABLE IF NOT EXISTS http_request_log (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  run_id TEXT NOT NULL,
  job_id TEXT NOT NULL,
  source_name TEXT NOT NULL,
  source_family TEXT NOT NULL,
  station_key TEXT,
  action TEXT NOT NULL,
  request_url_or_key TEXT NOT NULL,
  http_method TEXT NOT NULL,
  status_code INTEGER,
  issue_time_utc TEXT,
  valid_time_utc TEXT,
  duration_ms REAL,
  bytes_downloaded INTEGER,
  rows_parsed INTEGER,
  retry_count INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL,
  exception_class TEXT,
  exception_message TEXT,
  created_at_utc TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS object_manifest (
  object_id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL,
  station_key TEXT,
  source_name TEXT NOT NULL,
  source_family TEXT NOT NULL,
  source_identifier TEXT,
  request_url_or_bucket_key TEXT NOT NULL,
  requested_range_start_utc TEXT,
  requested_range_end_utc TEXT,
  cycle_time_utc TEXT,
  forecast_hour INTEGER,
  domain_name TEXT,
  http_status INTEGER,
  content_length INTEGER,
  checksum_sha256 TEXT NOT NULL,
  payload_encoding TEXT,
  payload_text TEXT,
  payload_blob BLOB,
  parser_status TEXT NOT NULL,
  row_count INTEGER NOT NULL DEFAULT 0,
  duplicate_of_checksum TEXT,
  extraction_status TEXT,
  grib_message_count INTEGER,
  ingested_at_utc TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS parser_run (
  parser_run_id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL,
  source_name TEXT NOT NULL,
  parser_version TEXT NOT NULL,
  object_id TEXT,
  status TEXT NOT NULL,
  rows_parsed INTEGER NOT NULL DEFAULT 0,
  duration_ms REAL,
  details_json TEXT,
  created_at_utc TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS normalized_partition (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  run_id TEXT NOT NULL,
  dataset_name TEXT NOT NULL,
  station_key TEXT,
  partition_date_utc TEXT,
  row_count INTEGER NOT NULL DEFAULT 0,
  checksum_sha256 TEXT,
  details_json TEXT,
  created_at_utc TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS source_inventory (
  inventory_key TEXT PRIMARY KEY,
  station_key TEXT NOT NULL,
  source_name TEXT NOT NULL,
  source_family TEXT NOT NULL,
  item_type TEXT NOT NULL,
  item_key TEXT NOT NULL,
  issue_time_utc TEXT,
  valid_time_utc TEXT,
  status TEXT NOT NULL,
  details_json TEXT,
  created_at_utc TEXT NOT NULL,
  updated_at_utc TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS source_gap_audit (
  gap_id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL,
  station_key TEXT NOT NULL,
  source_name TEXT NOT NULL,
  gap_start_utc TEXT,
  gap_end_utc TEXT,
  expected_count INTEGER,
  actual_count INTEGER,
  status TEXT NOT NULL,
  details_json TEXT,
  created_at_utc TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS cli_daily_label (
  station_key TEXT NOT NULL,
  target_date_local TEXT NOT NULL,
  tmax_f REAL,
  tmin_f REAL,
  tavg_f REAL,
  max_obs_time_local TEXT,
  min_obs_time_local TEXT,
  precip_in REAL,
  snow_in REAL,
  sky_cover TEXT,
  source_issue_time_utc TEXT,
  source_payload_year INTEGER,
  source_name TEXT NOT NULL,
  source_family TEXT NOT NULL,
  source_identifier TEXT,
  request_url_or_bucket_key TEXT,
  issue_time_utc TEXT,
  valid_time_utc TEXT,
  ingested_at_utc TEXT NOT NULL,
  raw_object_sha256 TEXT NOT NULL,
  parser_version TEXT NOT NULL,
  label_disagreement_flag INTEGER NOT NULL DEFAULT 0,
  raw_cli_tmax_f REAL,
  raw_cli_tmin_f REAL,
  PRIMARY KEY (station_key, target_date_local)
);

CREATE TABLE IF NOT EXISTS cli_raw_text (
  station_key TEXT NOT NULL,
  pil TEXT NOT NULL,
  product_timestamp_utc TEXT NOT NULL,
  issued_by_center TEXT,
  local_report_date TEXT,
  max_temp_f REAL,
  max_temp_local_time TEXT,
  min_temp_f REAL,
  min_temp_local_time TEXT,
  text_body TEXT NOT NULL,
  source_name TEXT NOT NULL,
  source_family TEXT NOT NULL,
  source_identifier TEXT,
  request_url_or_bucket_key TEXT,
  issue_time_utc TEXT,
  valid_time_utc TEXT,
  ingested_at_utc TEXT NOT NULL,
  raw_object_sha256 TEXT NOT NULL,
  parser_version TEXT NOT NULL,
  PRIMARY KEY (station_key, pil, product_timestamp_utc)
);

CREATE TABLE IF NOT EXISTS asos_hourly_obs (
  station_key TEXT NOT NULL,
  valid_time_utc TEXT NOT NULL,
  tmpf REAL,
  dwpf REAL,
  relh REAL,
  drct REAL,
  sknt REAL,
  p01i REAL,
  alti REAL,
  mslp REAL,
  vsby REAL,
  gust REAL,
  skyc1 TEXT,
  skyc2 TEXT,
  skyc3 TEXT,
  skyc4 TEXT,
  skyl1 REAL,
  skyl2 REAL,
  skyl3 REAL,
  skyl4 REAL,
  wxcodes TEXT,
  feel REAL,
  metar_raw TEXT,
  snowdepth REAL,
  obs_day_lstd TEXT,
  max_so_far_tmpf_in_obs_day REAL,
  min_so_far_tmpf_in_obs_day REAL,
  temp_trend_1h REAL,
  temp_trend_3h REAL,
  temp_trend_6h REAL,
  dewpoint_trend_1h REAL,
  wind_trend_1h REAL,
  source_name TEXT NOT NULL,
  source_family TEXT NOT NULL,
  source_identifier TEXT,
  request_url_or_bucket_key TEXT,
  issue_time_utc TEXT,
  ingested_at_utc TEXT NOT NULL,
  raw_object_sha256 TEXT NOT NULL,
  parser_version TEXT NOT NULL,
  PRIMARY KEY (station_key, valid_time_utc)
);

CREATE TABLE IF NOT EXISTS asos_1min_obs (
  station_key TEXT NOT NULL,
  valid_time_utc TEXT NOT NULL,
  tmpf REAL,
  dwpf REAL,
  drct REAL,
  sknt REAL,
  aggregate_5m_json TEXT,
  aggregate_15m_json TEXT,
  source_name TEXT NOT NULL,
  source_family TEXT NOT NULL,
  source_identifier TEXT,
  request_url_or_bucket_key TEXT,
  issue_time_utc TEXT,
  ingested_at_utc TEXT NOT NULL,
  raw_object_sha256 TEXT NOT NULL,
  parser_version TEXT NOT NULL,
  PRIMARY KEY (station_key, valid_time_utc)
);

CREATE TABLE IF NOT EXISTS mos_station_guidance (
  station_key TEXT NOT NULL,
  model_name TEXT NOT NULL,
  runtime_utc TEXT NOT NULL,
  valid_time_utc TEXT NOT NULL,
  lead_hours INTEGER,
  mos_target_day_local TEXT,
  max_temp_guidance_f REAL,
  min_temp_guidance_f REAL,
  hourly_temp_f REAL,
  dew_point_f REAL,
  cloud_category TEXT,
  wind_direction_deg REAL,
  wind_speed_kt REAL,
  precip_prob REAL,
  thunder_prob REAL,
  qpf REAL,
  ceiling_ft REAL,
  visibility_mi REAL,
  above_45 INTEGER,
  above_46 INTEGER,
  above_47 INTEGER,
  above_48 INTEGER,
  above_49 INTEGER,
  above_50 INTEGER,
  raw_values_json TEXT,
  source_name TEXT NOT NULL,
  source_family TEXT NOT NULL,
  source_identifier TEXT,
  request_url_or_bucket_key TEXT,
  issue_time_utc TEXT,
  ingested_at_utc TEXT NOT NULL,
  raw_object_sha256 TEXT NOT NULL,
  parser_version TEXT NOT NULL,
  PRIMARY KEY (station_key, model_name, runtime_utc, valid_time_utc)
);

CREATE TABLE IF NOT EXISTS ndfd_point_forecast (
  station_key TEXT NOT NULL,
  issue_time_utc TEXT NOT NULL,
  valid_time_utc TEXT NOT NULL,
  live_or_historical TEXT NOT NULL,
  temp_f REAL,
  maxt_f REAL,
  mint_f REAL,
  sky_pct REAL,
  wind_speed REAL,
  wind_dir REAL,
  qpf REAL,
  pop12 REAL,
  implied_daily_max_f REAL,
  source_name TEXT NOT NULL,
  source_family TEXT NOT NULL,
  source_identifier TEXT,
  request_url_or_bucket_key TEXT,
  ingested_at_utc TEXT NOT NULL,
  raw_object_sha256 TEXT NOT NULL,
  parser_version TEXT NOT NULL,
  PRIMARY KEY (station_key, issue_time_utc, valid_time_utc, live_or_historical)
);

CREATE TABLE IF NOT EXISTS model_point_extract (
  station_key TEXT NOT NULL,
  model_name TEXT NOT NULL,
  cycle_time_utc TEXT NOT NULL,
  valid_time_utc TEXT NOT NULL,
  forecast_hour INTEGER NOT NULL,
  variable_name TEXT NOT NULL,
  nearest_value REAL,
  bilinear_value REAL,
  nbr_mean REAL,
  nbr_min REAL,
  nbr_max REAL,
  nbr_std REAL,
  grid_source_lat REAL,
  grid_source_lon REAL,
  grid_distance_km REAL,
  interpolation_method TEXT,
  source_name TEXT NOT NULL,
  source_family TEXT NOT NULL,
  source_identifier TEXT,
  request_url_or_bucket_key TEXT,
  issue_time_utc TEXT,
  ingested_at_utc TEXT NOT NULL,
  raw_object_sha256 TEXT NOT NULL,
  parser_version TEXT NOT NULL,
  PRIMARY KEY (station_key, model_name, cycle_time_utc, valid_time_utc, forecast_hour, variable_name)
);

CREATE TABLE IF NOT EXISTS threadex_daily_aux (
  station_key TEXT NOT NULL,
  threadex_id TEXT NOT NULL,
  date_local TEXT NOT NULL,
  maxt_f REAL,
  mint_f REAL,
  pcpn_in REAL,
  snow_in REAL,
  auxiliary_only INTEGER NOT NULL,
  not_label_of_truth INTEGER NOT NULL,
  metadata_json TEXT,
  source_name TEXT NOT NULL,
  source_family TEXT NOT NULL,
  source_identifier TEXT,
  request_url_or_bucket_key TEXT,
  issue_time_utc TEXT,
  ingested_at_utc TEXT NOT NULL,
  raw_object_sha256 TEXT NOT NULL,
  parser_version TEXT NOT NULL,
  PRIMARY KEY (station_key, threadex_id, date_local)
);

CREATE TABLE IF NOT EXISTS climate_normals_daily (
  station_key TEXT NOT NULL,
  day_of_year INTEGER NOT NULL,
  normal_tmax_f REAL,
  normal_tmin_f REAL,
  normal_tavg_f REAL,
  static_prior INTEGER NOT NULL,
  not_observation INTEGER NOT NULL,
  not_forecast INTEGER NOT NULL,
  source_name TEXT NOT NULL,
  source_family TEXT NOT NULL,
  source_identifier TEXT,
  request_url_or_bucket_key TEXT,
  ingested_at_utc TEXT NOT NULL,
  raw_object_sha256 TEXT NOT NULL,
  parser_version TEXT NOT NULL,
  PRIMARY KEY (station_key, day_of_year)
);

CREATE TABLE IF NOT EXISTS climate_normals_hourly (
  station_key TEXT NOT NULL,
  day_of_year INTEGER NOT NULL,
  hour_local_standard INTEGER NOT NULL,
  normal_temp_f REAL,
  static_prior INTEGER NOT NULL,
  not_observation INTEGER NOT NULL,
  not_forecast INTEGER NOT NULL,
  source_name TEXT NOT NULL,
  source_family TEXT NOT NULL,
  source_identifier TEXT,
  request_url_or_bucket_key TEXT,
  ingested_at_utc TEXT NOT NULL,
  raw_object_sha256 TEXT NOT NULL,
  parser_version TEXT NOT NULL,
  PRIMARY KEY (station_key, day_of_year, hour_local_standard)
);

CREATE TABLE IF NOT EXISTS climodat_daily_aux (
  station_key TEXT NOT NULL,
  date_localish TEXT NOT NULL,
  high_f REAL,
  low_f REAL,
  precip_in REAL,
  snow_in REAL,
  snowdepth_in REAL,
  estimated_flags_json TEXT,
  auxiliary_only INTEGER NOT NULL,
  not_label_of_truth INTEGER NOT NULL,
  source_name TEXT NOT NULL,
  source_family TEXT NOT NULL,
  source_identifier TEXT,
  request_url_or_bucket_key TEXT,
  issue_time_utc TEXT,
  ingested_at_utc TEXT NOT NULL,
  raw_object_sha256 TEXT NOT NULL,
  parser_version TEXT NOT NULL,
  PRIMARY KEY (station_key, date_localish)
);

CREATE TABLE IF NOT EXISTS lcdv2_hourly_aux (
  station_key TEXT NOT NULL,
  valid_time_utc TEXT NOT NULL,
  data_json TEXT NOT NULL,
  source_name TEXT NOT NULL,
  source_family TEXT NOT NULL,
  source_identifier TEXT,
  request_url_or_bucket_key TEXT,
  issue_time_utc TEXT,
  ingested_at_utc TEXT NOT NULL,
  raw_object_sha256 TEXT NOT NULL,
  parser_version TEXT NOT NULL,
  PRIMARY KEY (station_key, valid_time_utc)
);

CREATE TABLE IF NOT EXISTS lcdv2_daily_aux (
  station_key TEXT NOT NULL,
  date_local TEXT NOT NULL,
  data_json TEXT NOT NULL,
  source_name TEXT NOT NULL,
  source_family TEXT NOT NULL,
  source_identifier TEXT,
  request_url_or_bucket_key TEXT,
  issue_time_utc TEXT,
  ingested_at_utc TEXT NOT NULL,
  raw_object_sha256 TEXT NOT NULL,
  parser_version TEXT NOT NULL,
  PRIMARY KEY (station_key, date_local)
);

CREATE TABLE IF NOT EXISTS decision_snapshot_feature_set (
  station_key TEXT NOT NULL,
  target_day_local TEXT NOT NULL,
  decision_time_utc TEXT NOT NULL,
  snapshot_version TEXT NOT NULL,
  snapshot_json TEXT NOT NULL,
  missing_sources_json TEXT,
  created_at_utc TEXT NOT NULL,
  PRIMARY KEY (station_key, target_day_local, decision_time_utc, snapshot_version)
);
