CREATE SCHEMA IF NOT EXISTS wunderground_ml;

CREATE TABLE IF NOT EXISTS wunderground_ml.wunderground_station_observation_30m (
  id BIGINT NOT NULL AUTO_INCREMENT,
  api_call_id BIGINT NOT NULL,
  request_location_id VARCHAR(64) NOT NULL,
  obs_id VARCHAR(32) NOT NULL,
  obs_key VARCHAR(32) NULL,
  obs_name VARCHAR(255) NULL,
  valid_time_gmt BIGINT NOT NULL,
  valid_time_utc DATETIME NOT NULL,
  day_ind CHAR(1) NULL,
  temp INT NULL,
  dew_pt INT NULL,
  heat_index INT NULL,
  rh INT NULL,
  pressure DECIMAL(10, 4) NULL,
  pressure_tend INT NULL,
  pressure_desc VARCHAR(64) NULL,
  vis DECIMAL(10, 4) NULL,
  wc INT NULL,
  wdir INT NULL,
  wdir_cardinal VARCHAR(16) NULL,
  gust INT NULL,
  wspd INT NULL,
  wx_phrase VARCHAR(255) NULL,
  wx_icon INT NULL,
  icon_extd INT NULL,
  precip_total DECIMAL(10, 4) NULL,
  precip_hrly DECIMAL(10, 4) NULL,
  snow_hrly DECIMAL(10, 4) NULL,
  max_temp INT NULL,
  min_temp INT NULL,
  uv_desc VARCHAR(64) NULL,
  uv_index INT NULL,
  feels_like INT NULL,
  clds VARCHAR(64) NULL,
  qualifier VARCHAR(64) NULL,
  qualifier_svrty VARCHAR(64) NULL,
  blunt_phrase VARCHAR(255) NULL,
  terse_phrase VARCHAR(255) NULL,
  observation_class VARCHAR(32) NULL,
  water_temp INT NULL,
  primary_wave_period DECIMAL(10, 4) NULL,
  primary_wave_height DECIMAL(10, 4) NULL,
  primary_swell_period DECIMAL(10, 4) NULL,
  primary_swell_height DECIMAL(10, 4) NULL,
  primary_swell_direction INT NULL,
  secondary_swell_period DECIMAL(10, 4) NULL,
  secondary_swell_height DECIMAL(10, 4) NULL,
  secondary_swell_direction INT NULL,
  created_at_utc DATETIME NOT NULL,
  updated_at_utc DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (request_location_id, obs_id, valid_time_gmt)
);

CREATE INDEX idx_wu_obs30m_request_valid
  ON wunderground_ml.wunderground_station_observation_30m (request_location_id, valid_time_gmt);

CREATE INDEX idx_wu_obs30m_obs_valid
  ON wunderground_ml.wunderground_station_observation_30m (obs_id, valid_time_gmt);

CREATE INDEX idx_wu_obs30m_api_call
  ON wunderground_ml.wunderground_station_observation_30m (api_call_id);

INSERT INTO wunderground_ml.wunderground_station_observation_30m (
  id,
  api_call_id,
  request_location_id,
  obs_id,
  obs_key,
  obs_name,
  valid_time_gmt,
  valid_time_utc,
  day_ind,
  temp,
  dew_pt,
  heat_index,
  rh,
  pressure,
  pressure_tend,
  pressure_desc,
  vis,
  wc,
  wdir,
  wdir_cardinal,
  gust,
  wspd,
  wx_phrase,
  wx_icon,
  icon_extd,
  precip_total,
  precip_hrly,
  snow_hrly,
  max_temp,
  min_temp,
  uv_desc,
  uv_index,
  feels_like,
  clds,
  qualifier,
  qualifier_svrty,
  blunt_phrase,
  terse_phrase,
  observation_class,
  water_temp,
  primary_wave_period,
  primary_wave_height,
  primary_swell_period,
  primary_swell_height,
  primary_swell_direction,
  secondary_swell_period,
  secondary_swell_height,
  secondary_swell_direction,
  created_at_utc,
  updated_at_utc
)
SELECT
  id,
  api_call_id,
  request_location_id,
  obs_id,
  obs_key,
  obs_name,
  valid_time_gmt,
  valid_time_utc,
  day_ind,
  temp,
  dew_pt,
  heat_index,
  rh,
  pressure,
  pressure_tend,
  pressure_desc,
  vis,
  wc,
  wdir,
  wdir_cardinal,
  gust,
  wspd,
  wx_phrase,
  wx_icon,
  icon_extd,
  precip_total,
  precip_hrly,
  snow_hrly,
  max_temp,
  min_temp,
  uv_desc,
  uv_index,
  feels_like,
  clds,
  qualifier,
  qualifier_svrty,
  blunt_phrase,
  terse_phrase,
  observation_class,
  water_temp,
  primary_wave_period,
  primary_wave_height,
  primary_swell_period,
  primary_swell_height,
  primary_swell_direction,
  secondary_swell_period,
  secondary_swell_height,
  secondary_swell_direction,
  created_at_utc,
  updated_at_utc
FROM weathercom_observation;

CREATE TABLE IF NOT EXISTS wunderground_ml.wunderground_station_daily_max_temperature (
  id BIGINT NOT NULL AUTO_INCREMENT,
  request_location_id VARCHAR(64) NOT NULL,
  obs_id VARCHAR(32) NOT NULL,
  station_zoneid VARCHAR(64) NOT NULL,
  target_date_local DATE NOT NULL,
  max_temp_f INT NOT NULL,
  source_valid_time_gmt BIGINT NULL,
  source_api_call_id BIGINT NULL,
  source_type VARCHAR(32) NOT NULL,
  observation_count INT NOT NULL,
  created_at_utc DATETIME NOT NULL,
  updated_at_utc DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (request_location_id, obs_id, target_date_local)
);

CREATE INDEX idx_wu_daily_max_request_day
  ON wunderground_ml.wunderground_station_daily_max_temperature (request_location_id, target_date_local);

CREATE INDEX idx_wu_daily_max_obs_day
  ON wunderground_ml.wunderground_station_daily_max_temperature (obs_id, target_date_local);

CREATE INDEX idx_wu_daily_max_api_call
  ON wunderground_ml.wunderground_station_daily_max_temperature (source_api_call_id);

DROP TABLE IF EXISTS weathercom_observation;
